name: Rust

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo clippy --all --all-targets -- -Dwarnings

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test all-targets
      run: cargo test --workspace --all-targets
    - name: Test docs
      run: cargo test --workspace --doc

  docs:
    runs-on: ubuntu-latest
    name: Build-test docs
    steps:
    - uses: actions/checkout@v4
    - name: Document all crates
      env:
        RUSTDOCFLAGS: -Dwarnings
      run: cargo doc --all --all-features --no-deps --document-private-items
